language: python
python:
    - 3.7
    - 3.6
    - 3.5
    - 2.7
sudo: false
install:
    - pip install -U pip
    - pip install ".[test]" coveralls
script:
    - nosetests --with-coverage --cover-package traittypes traittypes
after_success:
    - coveralls
